select * from tab;
select * from tbl_member;
select * from TBL_GRADE;
SELECT sequence_name
FROM user_sequences;
desc tbl_member;
----- ==== *** 휴지통 조회하기 *** ==== -----
select * 
from user_recyclebin;

purge recyclebin;  -- 휴지통에 있던 모든 테이블들을 영구히 삭제하는 것이다.
-- Recyclebin이(가) 비워졌습니다.
commit;
drop sequence seq_department;

CREATE SEQUENCE seq_department
START WITH 10
INCREMENT BY 10
NOCACHE;
select * from TBL_DEPARTMENT;

delete from TBL_DEPARTMENT
where department_seq = '60';

insert into TBL_DEPARTMENT values(SEQ_DEPARTMENT.nextval, '인사팀');
insert into TBL_DEPARTMENT values(SEQ_DEPARTMENT.nextval, '개발팀');
insert into TBL_DEPARTMENT values(SEQ_DEPARTMENT.nextval, '기획팀');
insert into TBL_DEPARTMENT values(SEQ_DEPARTMENT.nextval, '영업팀');
insert into TBL_DEPARTMENT values(SEQ_DEPARTMENT.nextval, '고객지원팀');
commit;

insert into TBL_GRADE values(SEQ_GRADE.nextval, '사원');
insert into TBL_GRADE values(SEQ_GRADE.nextval, '대리');
insert into TBL_GRADE values(SEQ_GRADE.nextval, '과장');
insert into TBL_GRADE values(SEQ_GRADE.nextval, '부장');
insert into TBL_GRADE values(SEQ_GRADE.nextval, '사장');
commit;

drop SEQUENCE MEMBER_SEQ_GENERATOR;
CREATE SEQUENCE MEMBER_SEQ_GENERATOR
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
/

commit;

WITH
A AS
(SELECT department_name
      , COUNT(*) AS cnt
 FROM tbl_member E LEFT JOIN tbl_department D
 ON E.fk_department_seq = D.department_seq
 GROUP BY D.department_name)
,
B AS
(SELECT COUNT(*) AS totalcnt
 FROM tbl_member)
SELECT NVL(department_name, '부서없음') AS department_name, 
       cnt, 
       ROUND((cnt/totalcnt)*100, 2) AS percentage
FROM A CROSS JOIN B 
ORDER BY cnt DESC, A.department_name ASC;

with
A as
(
select member_gender as gender, count(*) as cnt
from tbl_member
group by member_gender
)
,
B as
(
select count(*) as totalcnt
from tbl_member
)
select gender,
    cnt,
    ROUND((cnt/totalcnt)*100, 2) AS percentage
FROM A CROSS JOIN B
order by cnt desc;

desc TBL_CALENDAR;
desc TBL_CALENDAR_BIG_CATEGORY;
desc TBL_CALENDAR_SMALL_CATEGORY;
select * from tab;
select * from TBL_CALENDAR;

select *
from TBL_DRAFT;

drop table TBL_EMAIL;

CREATE TABLE TBL_EMAIL (
    email_seq NUMBER PRIMARY KEY,
    send_member_email VARCHAR2(50) NOT NULL,
    receive_member_email VARCHAR2(50),
    email_send_orgno NUMBER,
    email_receive_orgno NUMBER,
    email_title VARCHAR2(50),
    email_content CLOB,
    email_regdate DATE DEFAULT SYSDATE,
    email_send_status NUMBER(1) DEFAULT 0,
    email_receive_status NUMBER(1) DEFAULT 0,
    email_filename VARCHAR2(255),
    email_orgfilename VARCHAR2(255),
    email_filesize VARCHAR2(255),
    email_send_important NUMBER(1) DEFAULT 0,
    email_receive_important NUMBER(1) DEFAULT 0,
    email_readstatus NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_email_send_member_email FOREIGN KEY (send_member_email)
        REFERENCES TBL_MEMBER(member_email)
);
drop table TBL_EMAIL;

CREATE SEQUENCE emailSeq
START WITH 1
INCREMENT BY 1
NOCACHE;

select * from tbl_member;
desc tbl_member;
select * from tab;
select * from tbl_vacation;
desc tbl_vacation;
select * from tbl_business;
desc tbl_business;
select * from tbl_payment;
select * from tbl_business_conform;

select * from tab;
select * from tbl_member;
select * from tbl_email;
delete from tbl_email;
select * from TBL_EMAIL_USER_STATUS;

desc tbl_email;
rollback;
commit;

select count(*)
from tbl_email;

drop table TBL_EMAIL;
drop table TBL_EMAIL_USER_STATUS;
CREATE TABLE TBL_EMAIL (
    email_seq NUMBER PRIMARY KEY,
    send_member_email VARCHAR2(50) NOT NULL,
    receive_member_email VARCHAR2(50) NOT NULL,
    email_title VARCHAR2(50),
    email_content CLOB,
    email_regdate DATE DEFAULT SYSDATE,
    email_filename VARCHAR2(255),
    email_orgfilename VARCHAR2(255),
    email_filesize VARCHAR2(255),
    CONSTRAINT fk_email_send_member_email FOREIGN KEY (send_member_email)
        REFERENCES TBL_MEMBER(member_email)
);

CREATE TABLE TBL_EMAIL_USER_STATUS (
    email_seq NUMBER NOT NULL,
    member_email VARCHAR2(50) NOT NULL,
    read_status NUMBER(1) DEFAULT 0,           -- 읽음 상태
    important_status NUMBER(1) DEFAULT 0,       -- 중요 표시
    PRIMARY KEY (email_seq, member_email),
    CONSTRAINT fk_email_user_email FOREIGN KEY (email_seq)
        REFERENCES TBL_EMAIL(email_seq),
    CONSTRAINT fk_email_user_member FOREIGN KEY (member_email)
        REFERENCES TBL_MEMBER(member_email)
);

CREATE TABLE documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(100),
    content CLOB,
    embedding CLOB
);

select * from DOCUMENT;
delete from DOCUMENT;
-- 시퀀스 생성
CREATE SEQUENCE DOCUMENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- DOCUMENT 테이블 생성
CREATE TABLE DOCUMENT (
    ID          NUMBER(20) PRIMARY KEY,
    TABLE_NAME  VARCHAR2(100) NOT NULL,
    COLUMN_NAME VARCHAR2(100) NOT NULL,
    VALUE       VARCHAR2(4000),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE DOCUMENT MODIFY COLUMN_NAME VARCHAR2(200);

commit;
